/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encrypt */

#ifndef _Included_Encrypt
#define _Included_Encrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Encrypt
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Encrypt_encrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
